const rugs =  {
    product: {
        id: 149701,
            sku: '5810_VNE10_yellow',
            name: 'Jaipur Living Vienne VNE10 Beige Power Loomed Silk Rug',
            description: 'The elegant Vienne collection showcases the on-trend blanc de blanc look for an effortless and luxuriously vintage statement. The Lourdes rug boasts a subtly distressed mosaic motif in warm tones of cream, taupe, and ivory with accents of metallic gold. Soft and lustrous, this chameleon-like design emulates the timeless style of a Turkish hand-knotted rug, but in an accessible polyester and viscose power-loomed quality.',
            category: 'Assorted Traditional Rugs',
            collection: 'Assorted Transitional Rugs',
            vendor: 'Jaipur Rugs',
            designer: '',
            madeIn: 'Turkey',
            material: 'Silk',
            quality: 'Power Loomed',
            image: 'https://www.modernrugs.com/rug_images/5810_VNE10_yellow_medium.jpg',
            attributes: [
                {name: "distressed", group: "design", value: "distressed"},
                {name: "patterned", group: "design", value: "patterned"},
                {name: "silk", group: "material", value: "silk"},
                {name: "transitional", group: "design", value: "transitional"}],
            variations: [
            {
                option: 1,
                active: 1,
                sizeSku: "RUG146931",
                GS1: "887962826523",
                size: "2'6\" x 8' runner",
                searchSize: "8' runner",
                aliasSize: "8' runner",
                searchSizeFloor: "8' runner",
                shape: "Runner",
                oldPrice: 0,
                sale: "",
                price: 222,
                stock: 1,
                width: 30,
                length: 96,
                height: 0.4,
                shippingLength: 31,
                shippingWidth: 6,
                shippingHeight: 6,
                shippingWeight: 9.4,
                shippingType: "Small Parcel",
                origMap: 222,
                wholesale: 120,
                MSRP: 266
            },
            {
                option: 2,
                active: 1,
                sizeSku: "RUG146932",
                GS1: "887962826530",
                size: "2'6\" x 12' runner",
                searchSize: "12' runner",
                aliasSize: "12' runner",
                searchSizeFloor: "12' runner",
                shape: "Runner",
                oldPrice: 0,
                sale: "",
                price: 333,
                stock: 1,
                width: 30,
                length: 144,
                height: 0.4,
                shippingLength: 31,
                shippingWidth: 9,
                shippingHeight: 9,
                shippingWeight: 14.1,
                shippingType: "Small Parcel",
                origMap: 333,
                wholesale: 180,
                MSRP: 400
            }, {
                option: 3,
                active: 1,
                sizeSku: "RUG146929",
                GS1: "887962826509",
                size: "5' x 7'6\"",
                searchSize: "5 x 8",
                aliasSize: "5 x 8",
                searchSizeFloor: "5 x 8",
                shape: "Rectangle",
                oldPrice: 0,
                sale: "",
                price: 375,
                stock: 1,
                width: 60,
                length: 90,
                height: 0.4,
                shippingLength: 61,
                shippingWidth: 6,
                shippingHeight: 6,
                shippingWeight: 17.63,
                shippingType: "Small Parcel",
                origMap: 375,
                wholesale: 205,
                MSRP: 455
            }, {
                option: 4,
                active: 1,
                sizeSku: "RUG146930",
                GS1: "887962826516",
                size: "7'10\" x 10'10\"",
                searchSize: "8 x 10",
                aliasSize: "8 x 10",
                searchSizeFloor: "8 x 10",
                shape: "Rectangle",
                oldPrice: 0,
                sale: "",
                price: 855,
                stock: 1,
                width: 94,
                length: 130,
                height: 0.4,
                shippingLength: 95,
                shippingWidth: 8,
                shippingHeight: 8,
                shippingWeight: 39.88,
                shippingType: "Small Parcel",
                origMap: 855,
                wholesale: 465,
                MSRP: 1025
            }, {
                option: 5,
                active: 1,
                sizeSku: "RUG146933",
                GS1: "887962826547",
                size: "9'6\" x 12'6\"",
                searchSize: "9 x 12",
                aliasSize: "9 x 12",
                searchSizeFloor: "9 x 12",
                shape: "Rectangle",
                oldPrice: 0,
                sale: "",
                price: 1375,
                stock: 1,
                width: 114,
                length: 150,
                height: 0.4,
                shippingLength: 115,
                shippingWidth: 9,
                shippingHeight: 9,
                shippingWeight: 55.81,
                shippingType: "LTL",
                origMap: 1375,
                wholesale: 745,
                MSRP: 1655
            }],
            dateAdded: '2020-08-12'
    },
    customer: {
        id: 9022,
        firstName: 'Cristian',
        lastName: 'Kondratiuk',
        street: '1408 N 3rd st',
        astate: 'PA',
        city: 'Harrisburg',
        country: 'US',
        zip: 17102,
        email: 'cristianair@gmail.com',
        phone: '+1(717) 592-1775'
    },
    order: [
        {
            sku: '5810_VNE10_yellow',
            qty: 1,
            variation: 2,
            price: 333
        }
    ]
}


const a = {
    "product": {
        "id": 149701,
        "sku": "5810_VNE10_yellow",
        "name": "Jaipur Living Vienne VNE10 Beige Power Loomed Silk Rug",
        "description": "The elegant Vienne collection showcases the on-trend blanc de blanc look for an effortless and luxuriously vintage statement. The Lourdes rug boasts a subtly distressed mosaic motif in warm tones of cream, taupe, and ivory with accents of metallic gold. Soft and lustrous, this chameleon-like design emulates the timeless style of a Turkish hand-knotted rug, but in an accessible polyester and viscose power-loomed quality.",
        "category": "Assorted Traditional Rugs",
        "collection": "Assorted Transitional Rugs",
        "vendor": "Jaipur Rugs",
        "designer": "",
        "madeIn": "Turkey",
        "material": "Silk",
        "quality": "Power Loomed",
        "image": "https://www.modernrugs.com/rug_images/5810_VNE10_yellow_medium.jpg",
        "attributes": [
            {"name": "distressed", "group": "design", "value": "distressed"},
            {"name": "patterned", "group": "design", "value": "patterned"},
            {"name": "silk", "group": "material", "value": "silk"},
            {"name": "transitional", "group": "design", "value": "transitional"}
        ],
        "variations": [
            {
                "option": 1,
                "active": 1,
                "sizeSku": "RUG146931",
                "GS1": "887962826523",
                "size": "2'6\" x 8' runner",
                "searchSize": "8' runner",
                "aliasSize": "8' runner",
                "searchSizeFloor": "8' runner",
                "shape": "Runner",
                "oldPrice": 0,
                "sale": "",
                "price": 222,
                "stock": 1,
                "width": 30,
                "length": 96,
                "height": 0.4,
                "shippingLength": 31,
                "shippingWidth": 6,
                "shippingHeight": 6,
                "shippingWeight": 9.4,
                "shippingType": "Small Parcel",
                "origMap": 222,
                "wholesale": 120,
                "MSRP": 266
            },
            {
                "option": 2,
                "active": 1,
                "sizeSku": "RUG146932",
                "GS1": "887962826530",
                "size": "2'6\" x 12' runner",
                "searchSize": "12' runnerr",
                "aliasSize": "12' runner",
                "searchSizeFloor": "12' runner",
                "shape": "Runner",
                "oldPrice": 0,
                "sale": "",
                "price": 333,
                "stock": 1,
                "width": 30,
                "length": 96,
                "height": 0.4,
                "shippingLength": 31,
                "shippingWidth": 9,
                "shippingHeight": 9,
                "shippingWeight": 9.4,
                "shippingType": "Small Parcel",
                "origMap": 333,
                "wholesale": 180,
                "MSRP": 400
            }, {
                "option": 3,
                "active": 1,
                "sizeSku": "RUG146929",
                "GS1": "887962826509",
                "size": "5' x 7'6\"r",
                "searchSize": "5 x 8",
                "aliasSize": "5 x 8",
                "searchSizeFloor": "5 x 8",
                "shape": "Runner",
                "oldPrice": 0,
                "sale": "",
                "price": 375,
                "stock": 1,
                "width": 30,
                "length": 96,
                "height": 0.4,
                "shippingLength": 31,
                "shippingWidth": 6,
                "shippingHeight": 6,
                "shippingWeight": 9.4,
                "shippingType": "Small Parcel",
                "origMap": 222,
                "wholesale": 120,
                "MSRP": 455
            }, {
                "option": 4,
                "active": 1,
                "sizeSku": "RUG146930",
                "GS1": "887962826516",
                "size": "7'10\" x 10'10\"",
                "searchSize": "8 x 10",
                "aliasSize": "8 x 10",
                "searchSizeFloor": "8 x 10r",
                "shape": "Runner",
                "oldPrice": 0,
                "sale": "",
                "price": 855,
                "stock": 1,
                "width": 30,
                "length": 96,
                "height": 0.4,
                "shippingLength": 31,
                "shippingWidth": 6,
                "shippingHeight": 6,
                "shippingWeight": 9.4,
                "shippingType": "Small Parcel",
                "origMap": 222,
                "wholesale": 120,
                "MSRP": 266
            }, {
                "option": 5,
                "active": 1,
                "sizeSku": "RUG146933",
                "GS1": "887962826547",
                "size": "9'6\" x 12'6\"",
                "searchSize": "9 x 12",
                "aliasSize": "9 x 12",
                "searchSizeFloor": "9 x 12",
                "shape": "Runner",
                "oldPrice": 0,
                "sale": "",
                "price": 1375,
                "stock": 1,
                "width": 30,
                "length": 96,
                "height": 0.4,
                "shippingLength": 31,
                "shippingWidth": 6,
                "shippingHeight": 6,
                "shippingWeight": 9.4,
                "shippingType": "Small Parcel",
                "origMap": 222,
                "wholesale": 120,
                "MSRP": 266
            }]
    },
    "customer": {
        "id": 9022,
        "firstName": "Cristian",
        "lastName": "Kondratiuk",
        "street": "1408 N 3rd st",
        "state": "PA",
        "city": "Harrisburg",
        "country": "US",
        "zip": 17102,
        "email": "cristianair@gmail.com",
        "phone": "+1(717) 592-1775"
    },
    "order": [
        {
            "sku": "5810_VNE10_yellow",
            "qty": 1,
            "variation": 2,
            "price": 333
        }
    ],
    "maskCart":"",
    "token":""
}
